<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Pablo Gomez" />


<title>R syntax and the tidyverse</title>

<script src="site_libs/header-attrs-2.21/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/flatly.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-6.4.0/css/all.min.css" rel="stylesheet" />
<link href="site_libs/font-awesome-6.4.0/css/v4-shims.min.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">CADMS</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Pre Workshop
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="Intro_to_R.html">Intro to R</a>
    </li>
    <li>
      <a href="Spatial_intro.html">Intro to Spatial data</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Contact
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="Instructors.html">
        <span class="fa fa-users"></span>
         
        Instructors
      </a>
    </li>
    <li>
      <a href="https://cadms.vetmed.ucdavis.edu">
        <span class="fa fa-server"></span>
         
        CADMS Website
      </a>
    </li>
    <li>
      <a href="mailto:jpgo@ucdavis.edu">
        <span class="fa fa-envelope"></span>
         
        Email
      </a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">R syntax and the tidyverse</h1>
<h4 class="author">Pablo Gomez</h4>

</div>


<div id="r-basics" class="section level1" number="1">
<h1><span class="header-section-number">1</span> R basics</h1>
<p>R is like a calculator, we can make mathematical operations, for
example:</p>
<pre class="r"><code>2 + 2</code></pre>
<pre><code>## [1] 4</code></pre>
<p>R is a object-oriented programming language, this means that we
create objects that contain information. In R you can achieve the same
results using different approaches, for example, to create an object we
just type a name for the object and assign it a value using the
operators <code>=</code> or <code>&lt;-</code>. We can make operations
with objects of the same type, for example:</p>
<pre class="r"><code>x = 2 # create a new object with the = operator
y &lt;- 2 # create a new object with the &lt;- operator
x + y # make a operation with the objects</code></pre>
<pre><code>## [1] 4</code></pre>
<div id="vectors-in-r" class="section level2" number="1.1">
<h2><span class="header-section-number">1.1</span> Vectors in R</h2>
<p>You can store more than one value using vectors, to create a vector
of numbers we use <code>c()</code>. For example, we will store a
sequence of numbers from 5 to 10 using 2 different approaches and then
ask R if the objects are the same.<br />
<strong>tip:</strong> using the keys “alt” + “-” will automatically add
the operator <code>&lt;-</code>. Choosing which assign operator to use
is a matter of preference, I personally think that is easier reading
code with the operator <code>&lt;-</code>, but a lot of people uses
<code>=</code>.</p>
<pre class="r"><code>x &lt;- c(5, 6, 7, 8, 9, 10) # create a sequence form 5 to 10
y = 5:10 # create the same sequence but with a different approach
x == y # ask R if the objects have the same information</code></pre>
<pre><code>## [1] TRUE TRUE TRUE TRUE TRUE TRUE</code></pre>
<p>Notice that in the previous example we compared two objects using
<code>==</code>, this is the way we tell R that we want to COMPARE and
not to assign (remember that to assign you use only one <code>=</code>
symbol).</p>
<p>When we have a vector, we can ask R specific values inside an
object.</p>
<pre class="r"><code># Here we ask the 3rd value from our sequence
x[3]</code></pre>
<pre><code>## [1] 7</code></pre>
<pre class="r"><code># Now we multiply the 3rd value of the x sequence times the 5th value of the y sequence
x[3] * y[5]</code></pre>
<pre><code>## [1] 63</code></pre>
</div>
<div id="functions" class="section level2" number="1.2">
<h2><span class="header-section-number">1.2</span> Functions</h2>
<p>R has a lot of base functions, but we can define new functions. When
using R studio, the key <em>Tab</em> will help us to auto complete, this
can help us a lot when we don’t remember the exact name of the functions
available. The best part of programming with R is that it has a very
active community. Since its open source, anyone can create functions and
compile them in a package (or library). we can download these packages
and access new functions.<br />
Functions in R require arguments, which we can see in the function
documentation or if we press the key <em>Tab</em> when we are inside the
function.</p>
<pre class="r"><code># To get the sum of a vector of numbers inside an object we use sum()
sum(x)</code></pre>
<pre><code>## [1] 45</code></pre>
<p>We can put functions inside function, for example, to get <span
class="math inline">\(\sqrt{\sum_1^n x}\)</span> the square root of a
sum of the numbers in x we can use:</p>
<pre class="r"><code>sqrt(sum(x))</code></pre>
<pre><code>## [1] 6.708204</code></pre>
<p>Making functions in R is not as complicated as it sounds and can be
very useful when we need to do repetitive work. To define a function we
need to include the arguments that we want for the function and what are
we doing with those arguments. For example, the following function has
only one argument which is a name (string) and just pastes some text
before and after:</p>
<pre class="r"><code>F1 &lt;- function(name){
  paste(&quot;Hola&quot;, name, &quot;! welcome to the R world (: !&quot;) # paste the name with some text
}

# Testing the function (Put your name)
F1(name = &quot;Pablo&quot;)</code></pre>
<pre><code>## [1] &quot;Hola Pablo ! welcome to the R world (: !&quot;</code></pre>
<p>Besides storing numbers in the objects in R, we can store text,
matrices, tables, spatial objects, images, and other types of objects.
Next we will import our own data and do some manipulation in R.</p>
<p><strong>Exercise:</strong> Create a function that performs the <span
class="math inline">\(\sqrt{\sum_1^n x}\)</span> operation you did
previously with the code <code>sqrt(sum(x))</code></p>
</div>
<div id="types-of-variables" class="section level2" number="1.3">
<h2><span class="header-section-number">1.3</span> Types of
variables</h2>
<p>There are different types of variables in R, so far we have used the
numeric and string types. If yo want to know what kind of variable is a
given object, you can use the function <code>class()</code>. Lets try
it.</p>
<pre class="r"><code>class(x)</code></pre>
<pre><code>## [1] &quot;numeric&quot;</code></pre>
<p><strong>Exercise: </strong> What kind of variable is the output from
the first function you defined <code>F1()</code>?</p>
<p>There are other type of variables that we will see later in the
course.</p>
<!-- **Introduce different type of variables in R (e.g. Numeric, String, Factor, Date)** -->
</div>
<div id="introducing-the-pipes" class="section level2" number="1.4">
<h2><span class="header-section-number">1.4</span> Introducing the
pipes</h2>
<p>The library <code>dplyr</code> has several functions that can help to
clean, create new variables, and modify our data in other ways.</p>
<pre class="r"><code># if we dont have installed the library we will need to install it using:
# install.packages(&quot;dplyr&quot;)
# we load the library:
library(dplyr)</code></pre>
<p><code>dplyr</code> introduces a new operator called <em>pipes</em>
(<code>%&gt;%</code>), which can connect several functions to an object.
This is an alternative to write several functions in a single “line of
code” in a more organized way. For example, if we want to execute a
function <code>F1()</code> followed by another function
<code>F2()</code> for the object <code>x</code>:</p>
<p><code>F2(F1(x))</code> is equivalent to
<code>x %&gt;% F1() %&gt;% F2()</code></p>
<p>As you can notice, to read the code <code>F2(F1(x))</code> we have to
go from the inside to the outside to see the order of execution of the
functions, but when we read <code>x %&gt;% F1() %&gt;% F2()</code> we
read from left to right, which is the same way we normally would read
any text in western language.</p>
<p><strong>Suggestion:</strong> we can use the keys <em>Ctrl</em> +
<em>shift</em> + <em>m</em> to insert the <code>%&gt;%</code>
operator.</p>
<pre class="r"><code># We previosly used this code to calculate the square root of the sum of x
sqrt(sum(x))</code></pre>
<pre><code>## [1] 6.708204</code></pre>
<p>Using the pipes we can do the same more organized, by writing the
order of execution from left to right.</p>
<pre class="r"><code>x %&gt;% # First we call the data
  sum() %&gt;% # Sum all the values
  sqrt() # Compute the square root</code></pre>
<pre><code>## [1] 6.708204</code></pre>
<p>You will notice that the outputs are exactly the same. Feel free to
use whatever syntax you prefer, but for this course we will use mostly
the pipes and writing the code from left to right.</p>
</div>
</div>
<div id="importing-datasets" class="section level1" number="2">
<h1><span class="header-section-number">2</span> Importing datasets</h1>
<p>R can import data in different formats. The most common are excel
files (<em>.csv</em>, <em>.xls</em> y <em>.xlsx</em>), text files
<em>.txt</em> and spatial data <em>.shp</em>, which we will talk about
more in detail later.<br />
To read <em>.xls</em>, <em>.xlsx</em> and <em>.shp</em> files we will
need to install some libraries. To install a new library you need to be
connected to the internet and use the function
<code>install.packages()</code> to install the library. Once it has been
installed, you can load the library using the function
<code>library()</code>.</p>
<p>Download the excel file from this <a
href="https://ucdavis.app.box.com/folder/174771408063?s=cltv7bcwblxw5v90z5l56ognt9dprehv">link</a>.
It’s not necessary to have a Box account.</p>
<p><em>Suggestion:</em> Sometimes when we want to use only one function
from a library, we can just write the name of the library followed by
the operator <code>::</code> and the name of the function, for example:
<code>package::function()</code>. This way we won’t have to load the
whole library.</p>
<pre class="r"><code># If we dont have the library installed, we use:
# install.packages(&quot;readxl&quot;)

# Import the excel file
PRRS &lt;- readxl::read_xlsx(&quot;Data/PRRS.xlsx&quot;)</code></pre>
<p>The most popular format for tables in R are called
<code>data.frame</code>, when we import the data from a <em>.csv</em> o
<em>.xlsx</em>. We can examine what kind of object it is using the
function <code>class()</code>:</p>
<pre class="r"><code># Ask the class of a given object
class(PRRS)</code></pre>
<pre><code>## [1] &quot;tbl_df&quot;     &quot;tbl&quot;        &quot;data.frame&quot;</code></pre>
<p>It is possible that objects can have more than 1 class. In the
previous example, you can notice that the <code>PRRS</code> object has 3
different types of class.</p>
</div>
<div id="data-manipulation" class="section level1" number="3">
<h1><span class="header-section-number">3</span> Data manipulation</h1>
<p>In the following section we will cover some basics of data
manipulation, this includes create, modify and summarise variables in
our data.</p>
<div id="reducing-our-data" class="section level2" number="3.1">
<h2><span class="header-section-number">3.1</span> Reducing our
data</h2>
<p>Sometimes we want to select specific columns and rows on our data to
reduce the dimentionality, for this we can use the functions:</p>
<ul>
<li><code>select()</code> to select specific <em>columns</em></li>
<li><code>slice()</code> to select specific <em>rows</em> based on
position</li>
<li><code>filter()</code> to select specific <em>rows</em> based on a
condition</li>
</ul>
<div id="selecting-specific-columns" class="section level3"
number="3.1.1">
<h3><span class="header-section-number">3.1.1</span> Selecting specific
columns</h3>
<pre class="r"><code>PRRS %&gt;%  # the name of our data
  select(Result, farm_type) # we want to select only the columns Result and farm_type</code></pre>
<pre><code>## # A tibble: 1,353 × 2
##    Result farm_type
##    &lt;chr&gt;  &lt;chr&gt;    
##  1 No     sow farm 
##  2 No     sow farm 
##  3 No     sow farm 
##  4 Yes    sow farm 
##  5 Yes    sow farm 
##  6 Yes    sow farm 
##  7 Yes    sow farm 
##  8 Yes    sow farm 
##  9 Yes    sow farm 
## 10 Yes    sow farm 
## # ℹ 1,343 more rows</code></pre>
<p>We can also specify which columns we DON’T want to show in our
data:</p>
<pre class="r"><code>PRRS %&gt;% 
  select(-Age, -id) # with a &#39;-&#39; before the name we will exclude the column from the data</code></pre>
<pre><code>## # A tibble: 1,353 × 6
##    Result Sex   OtherSpecies name                    farm_type County       
##    &lt;chr&gt;  &lt;chr&gt;        &lt;dbl&gt; &lt;chr&gt;                   &lt;chr&gt;     &lt;chr&gt;        
##  1 No     H                0 Armstrong Research Farm sow farm  Pottawattamie
##  2 No     H                0 Armstrong Research Farm sow farm  Pottawattamie
##  3 No     H                0 Armstrong Research Farm sow farm  Pottawattamie
##  4 Yes    H                0 Armstrong Research Farm sow farm  Pottawattamie
##  5 Yes    H                0 Armstrong Research Farm sow farm  Pottawattamie
##  6 Yes    H                0 Armstrong Research Farm sow farm  Pottawattamie
##  7 Yes    M                0 Armstrong Research Farm sow farm  Pottawattamie
##  8 Yes    M                0 Armstrong Research Farm sow farm  Pottawattamie
##  9 Yes    M                0 Armstrong Research Farm sow farm  Pottawattamie
## 10 Yes    H                0 Armstrong Research Farm sow farm  Pottawattamie
## # ℹ 1,343 more rows</code></pre>
</div>
<div id="filtering-specific-rows" class="section level3" number="3.1.2">
<h3><span class="header-section-number">3.1.2</span> Filtering specific
rows</h3>
<p>Filtering columns works based on boolean logic, so we can specify a
condition and R will show only the rows that satisfy that condition. For
example, lets filter only the observations from boar studs:</p>
<pre class="r"><code>PRRS %&gt;% 
  filter(farm_type == &#39;boar studs&#39;) # we will use the equals to operator for this</code></pre>
<pre><code>## # A tibble: 0 × 8
## # ℹ 8 variables: Result &lt;chr&gt;, Sex &lt;chr&gt;, Age &lt;dbl&gt;, OtherSpecies &lt;dbl&gt;,
## #   id &lt;dbl&gt;, name &lt;chr&gt;, farm_type &lt;chr&gt;, County &lt;chr&gt;</code></pre>
</div>
</div>
<div id="creating-or-modifying-variables" class="section level2"
number="3.2">
<h2><span class="header-section-number">3.2</span> Creating or modifying
variables</h2>
<p>To create a new variable we can use the function
<code>mutate()</code>. For example, lets create a new variable that will
tell us if the farm type is a sow farm or not. For this we use the
variable <code>farm_type</code> which already contains information for
different farm types</p>
<pre class="r"><code># Creating a new variable
PRRS %&gt;% # name of the data set
  mutate( # mutate is the function we sue to create new variables
    SowFarm = ifelse(farm_type == &#39;sow farm&#39;, 1, 0) # we will create a binary variable where 1 = sow farm, 0 = Any other farm type
  ) </code></pre>
<pre><code>## # A tibble: 1,353 × 9
##    Result Sex     Age OtherSpecies    id name           farm_type County SowFarm
##    &lt;chr&gt;  &lt;chr&gt; &lt;dbl&gt;        &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;          &lt;chr&gt;     &lt;chr&gt;    &lt;dbl&gt;
##  1 No     H        18            0    23 Armstrong Res… sow farm  Potta…       1
##  2 No     H        60            0    23 Armstrong Res… sow farm  Potta…       1
##  3 No     H        60            0    23 Armstrong Res… sow farm  Potta…       1
##  4 Yes    H        36            0    23 Armstrong Res… sow farm  Potta…       1
##  5 Yes    H        50            0    23 Armstrong Res… sow farm  Potta…       1
##  6 Yes    H        16            0    23 Armstrong Res… sow farm  Potta…       1
##  7 Yes    M        15            0    23 Armstrong Res… sow farm  Potta…       1
##  8 Yes    M        22            0    23 Armstrong Res… sow farm  Potta…       1
##  9 Yes    M        30            0    23 Armstrong Res… sow farm  Potta…       1
## 10 Yes    H        14            0    23 Armstrong Res… sow farm  Potta…       1
## # ℹ 1,343 more rows</code></pre>
<p>Notice that in the previous code chunk, we did not assigned it to an
object, which means that R is just going to print it and dont save it.
To save it, remember that we use the assign operator <code>&lt;-</code>
or <code>=</code>.<br />
To modify an existing variable we can use the same function
<code>mutate()</code>, and specify what we want to replace the existing
variable with. For example, in the next chunk of code, we will modify
the variable <em>Sex</em>. The original variable has H for Female and M
for Male, so let’s change it to something that makes more sense:</p>
<pre class="r"><code># Now we will assign the new object to itself overwriting it.
PRRS &lt;- PRRS %&gt;%  # this is the data set we will use
  mutate( # we use the mutate function to create new variables
    Sex = recode( # The function recode, can be used similar to replace in excel
      Sex, # we will overwrite the variable Sex using the same name
      H = &#39;Female&#39;,
      M = &#39;Male&#39;
    )
  )</code></pre>
<p>Be careful when overwriting objects in R there is no undo for this.
It is important that your code is ordered and replicable in case you
make any mistake, so you can easily reach to your progress before the
mistake.</p>
</div>
<div id="grouping-and-summarizing-tables" class="section level2"
number="3.3">
<h2><span class="header-section-number">3.3</span> Grouping and
summarizing tables</h2>
<p>Often times we want to calculate summary statistics from our data, we
can group by a specific variable (or even multiple variables) to</p>
<pre class="r"><code># We can count how many observations for each of a variable name
PRRS %&gt;% 
  count(Result)</code></pre>
<pre><code>## # A tibble: 2 × 2
##   Result     n
##   &lt;chr&gt;  &lt;int&gt;
## 1 No       986
## 2 Yes      367</code></pre>
<p>The previous table show us that were 986 observations with test
result negative and 367 with test result positive. We can add multiple
variables to count</p>
<pre class="r"><code># We can count based on multiple variables
PRRS %&gt;% 
  count(Result, Sex)</code></pre>
<pre><code>## # A tibble: 4 × 3
##   Result Sex        n
##   &lt;chr&gt;  &lt;chr&gt;  &lt;int&gt;
## 1 No     Female   737
## 2 No     Male     249
## 3 Yes    Female   229
## 4 Yes    Male     138</code></pre>
<pre class="r"><code># PRRS %&gt;% 
  # count(Sex, wt = Result)</code></pre>
</div>
<div id="joining-datasets" class="section level2" number="3.4">
<h2><span class="header-section-number">3.4</span> Joining datasets</h2>
<pre class="r"><code># Importing the farm dataseet
nodes &lt;- read.csv(&quot;Data/node_attrib.csv&quot;)
# Importing the movement dataset
mov &lt;- read.csv(&quot;Data/network.csv&quot;)
# Get the number of outgoing and incoming shipments 
Out &lt;- mov %&gt;% 
  group_by(id_orig) %&gt;%
  summarise(Outgoing = n()) %&gt;%
  rename(id = id_orig)

In &lt;- mov %&gt;%
  group_by(id_dest) %&gt;%
  summarise(Incoming = n()) %&gt;% 
  rename(id = id_dest)

# Joining the two datasets
nodes &lt;- nodes %&gt;% 
  left_join(Out, by =&quot;id&quot;)

nodes &lt;- nodes %&gt;%
  left_join(In, by = &quot;id&quot;)

nodes</code></pre>
<pre><code>##    id                                                  name      lat      long
## 1   1                                 Iowa Select Farms Inc 42.50489 -93.26323
## 2   2                       Stanley Martins Fleckvieh Farms 43.08261 -91.56682
## 3   3                                  Centrum Valley Farms 42.66331 -93.63630
## 4   4                           Hilltop Farms fresh produce 41.71651 -93.90491
## 5   5                                         Hog Slat Inc. 42.25929 -91.15566
## 6   6                             Safari Iowa Hunting Farms 41.56854 -92.02317
## 7   7                                           Kloubec Koi 41.83465 -91.81982
## 8   8                                  Johnson Farms Supply 42.85789 -93.61687
## 9   9                                           Kroul Farms 41.87700 -91.47084
## 10 10                              Steve Robinson Farm Shop 41.96634 -91.19099
## 11 11                             Loess Hills Lavender Farm 41.67884 -95.93713
## 12 12                                     Uncle Bill&#39;s Farm 41.71713 -92.73772
## 13 13                                       Wild Woods Farm 41.70194 -91.47338
## 14 14                                Western Iowa Farms LLC 42.44647 -96.25294
## 15 15                                        Mushroom Mills 41.20559 -91.37005
## 16 16                                          Kruger Farms 42.41710 -92.69073
## 17 17                                         US Farm Lease 41.64893 -93.62416
## 18 18                                     Dawn Golden Farms 43.08464 -91.56918
## 19 19                            Kris Del Farms Corporation 41.62007 -90.64899
## 20 20 Lapp\x89\xf6_\xe5\xa9&#39;s Bee Supply and Honey Farm LLC 41.22699 -93.92651
## 21 21                          Nelson Pioneer Farm &amp; Museum 41.33235 -92.62145
## 22 22                                          WinMor Farms 41.71702 -92.65580
## 23 23                               Armstrong Research Farm 41.30823 -95.17208
## 24 24                                  Cinnamon Ridge Farms 41.71469 -90.69231
## 25 25                                  Rustik Rooster Farms 42.89116 -92.33734
## 26 26                                 Picket Fence Creamery 41.82968 -93.93218
## 27 27                          Doe&#39;s and Diva&#39;s Dairy, Inc. 41.46512 -95.82878
## 28 28                              Bushman Family Farms Inc 43.09108 -91.82770
## 29 29                                     Johnson Farms Inc 43.45690 -92.28017
## 30 30                                         Premier Grain 42.27013 -91.67477
## 31 31                                          Bethany Farm 41.56188 -94.88469
## 32 32               Farm Sweet Farm at Rosmann Family Farms 41.68048 -95.38560
## 33 33                                      Iowa Farm Family 42.30512 -93.29866
## 34 34   Iowa State University Horticulture Research Station 42.10658 -93.58981
## 35 35                                         RJM Farms Inc 43.11208 -94.76516
## 36 36                             Practical Farmers of Iowa 42.00683 -93.61690
## 37 37                                            Bass Farms 41.91948 -91.49390
## 38 38                                       A &amp; D Farms Inc 41.27141 -92.01188
## 39 39                                           Geno Source 41.89120 -92.06679
## 40 40                                          Tatonka Farm 42.53873 -92.10478
##    farm_type Outgoing Incoming
## 1   sow farm       30       13
## 2   sow farm       NA       33
## 3    nursery       13       NA
## 4   sow farm       15       35
## 5        GDU       33       14
## 6        GDU       11       47
## 7        GDU        3      116
## 8   sow farm       83      195
## 9    nursery        6       NA
## 10   nursery        1        7
## 11   nursery        1       NA
## 12   nursery        5       21
## 13   nursery       NA        2
## 14   nursery       15      121
## 15  finisher       NA       42
## 16  finisher        1       NA
## 17  finisher       68      821
## 18  finisher       NA       23
## 19  sow farm      397       45
## 20  finisher       27       NA
## 21   nursery       38       NA
## 22  sow farm       NA        1
## 23  sow farm       21       NA
## 24  sow farm       27        2
## 25       GDU      154        6
## 26  sow farm       NA        1
## 27   nursery        1       NA
## 28   nursery       22       NA
## 29   nursery      522       NA
## 30   nursery       12       34
## 31       GDU      101       27
## 32 boar stud       NA        1
## 33  sow farm       NA        1
## 34  sow farm       NA        1
## 35  sow farm       NA        1
## 36  sow farm       NA        1
## 37  sow farm        1       NA
## 38  sow farm        1       NA
## 39  sow farm        1       NA
## 40  sow farm        1       NA</code></pre>
<p>Now we will get the ones that had the higher number of movements:</p>
<pre class="r"><code>mov %&gt;% 
  group_by(id_orig) %&gt;% 
  summarise(N = n(), N_pigs = sum(pigs.moved)) %&gt;%
  arrange(desc(N)) %&gt;%
  head()</code></pre>
<pre><code>## # A tibble: 6 × 3
##   id_orig     N N_pigs
##     &lt;int&gt; &lt;int&gt;  &lt;int&gt;
## 1      29   522  50565
## 2      19   397  38686
## 3      25   154  15653
## 4      31   101  10711
## 5       8    83   7620
## 6      17    68   6633</code></pre>
<!-- ## Wide and Long formats -->
</div>
</div>
<div id="tables-in-r" class="section level1" number="4">
<h1><span class="header-section-number">4</span> Tables in R</h1>
<p>We can use the base R functions to create basic tables. For example,
we can create a table that shows the number of positive by sex:</p>
<pre class="r"><code>TBL &lt;- table(PRRS$Sex, PRRS$Result)
TBL</code></pre>
<pre><code>##         
##           No Yes
##   Female 737 229
##   Male   249 138</code></pre>
<p>When we have a table object we can ask for a specific column or row,
where is represented as [row, column].</p>
<pre class="r"><code>TBL[,2] # Get the second column</code></pre>
<pre><code>## Female   Male 
##    229    138</code></pre>
<!-- # Loops in R -->
</div>
<div id="exporting-the-data" class="section level1" number="5">
<h1><span class="header-section-number">5</span> Exporting the data</h1>
<pre class="r"><code>write.csv(nodes, &#39;Data/nodes.csv&#39;, row.names = F)</code></pre>
<hr />
<p><em>This lab has been developed with contributions from: <a
href="https://www.spablo-temporal.network">Jose Pablo
Gomez-Vazquez</a>.<br />
Feel free to use these training materials for your own research and
teaching. When using the materials we would appreciate using the proper
credits. If you would be interested in a training session, please
contact: <a href="mailto:jpgo@ucdavis.edu"
class="email">jpgo@ucdavis.edu</a></em></p>
<hr />
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
