---
title: "Topics for instructors"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = F, message = F, echo = F)
library(kableExtra); library(dplyr)
```

```{r TT schedule}
data.frame(
  Time = c('', '9:00-9:30', '9:30-10:30', '10:30-10:50', '10:50-12:00', '12:00-13:00', '13:00-14:00', '14:00-14:20', '14:20-15:00'),
  D01 = cell_spec(
    c('Data manipulation', 'Introduction to R studio', 'R syntax', 'Coffee break', 'Data reduction', 'Lunch', 'Data manupulation', 'Coffee break', 'Joining data'), 'html',
    link = c('slides/Day01.html', '1a_Intro_RstudioMarkdown.html', '1b_RandTidyverse.html', 'coffeeBreak.html', '1b_RandTidyverse.html', 'Lunch.html', '1b_RandTidyverse.html', 'coffeeBreak.html', '1b_RandTidyverse.html')
  ),
  D02 = cell_spec(
    c('Data visualization', 'Graphics in R I', 'Graphics in R II', 'Coffee break', 'Spatial Data', 'Lunch', 'Spatial Data II', 'Coffee break', 'Cartography'), 'html',
    link = c('slides/Day02.html', '1c_GraphicsI.html', '1c_GraphicsI.html', 'coffeeBreak.html', '2a_VectorsRasters.html', 'Lunch.html', '2a_VectorsRasters.html', 'coffeeBreak.html', '2a_VectorsRasters.html')
  ),
  D03 = cell_spec(
    c('Risk Assessment and SNA', 'Network analysis I', 'Network analysis II', 'Coffee break', 'Network analysis III', 'Lunch', 'Risk assessment I', 'Coffee break', 'Risk assessment II'), 'html',
    link = c('slides/Day-03.html', '3a_NetworkIntro.html', '3a_NetworkIntro.html', 'coffeeBreak.html', '3b_NetworkViz.html', 'Lunch.html', '4a_RiskAssessment.html', 'coffeeBreak.html', '4a_RiskAssessment.html')
  )
) %>%
  kbl("html", escape = FALSE, col.names = c('', 'May 16, 2023', 'May 17, 2023', 'May 18, 2023')) %>%
  kable_paper(full_width = F, lightable_options = c('hover')) %>%
  column_spec(1, bold = T, border_right = T) %>%
  column_spec(2, border_right = T) %>%
  column_spec(3, border_right = T) %>%
  column_spec(4, border_right = T) %>%
  row_spec(1, bold = T, extra_css = "border-bottom: 1px solid") %>%
  row_spec(c(4,6, 8), background = "#F6F5FA", italic = T)
```